# Outputs for the lambda function
Outputs:
  [CELL_ID]_Url:
    Description: The HTTP API Gateway url for the created lambda
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com

# HTTP API to expose the lambda function to the internet with no authentication
HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - "*"
        ExposeHeaders:
          - X-Total-Count
      FailOnWarnings: true

[CELL_ID]:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-[CELL_ID]
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: [CELL_ID]
      CodeUri: working/[CELL_ID]
      Handler: index.handler
      Runtime: nodejs18.x
      Events:
        HttpApiGET:
          Type: HttpApi
          Properties:
            Path: /[CELL_ID]
            Method: GET
            ApiId: !Ref HttpApi
# Add additional events or edit this one as required