# Outputs for the lambda function
Outputs:
  [CELL_ID]Url:
    Description: The HTTP API Gateway url for the created lambda
    Value: !Sub https://${[CELL_ID]HttpApi}.execute-api.${AWS::Region}.amazonaws.com

# HTTP API to expose the lambda function to the internet with no authentication
[CELL_ID]HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - "*"
        ExposeHeaders:
          - X-Total-Count
      FailOnWarnings: true
      DefinitionBody:
      Open API specification goes here

## This table example should be modified as little as possible to avoid errors
[CELL_ID]Table:
    Type: "AWS::DynamoDB::Table"
    Properties:
      ## Never change the billing mode from PAY_PER_REQUEST
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${AWS::StackName}-[CELL_ID]]
      ## never include any non-key attribute definitions in AttributeDefinitions
      AttributeDefinitions:
        - AttributeName: "ExampleId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ExampleId"
          KeyType: "HASH"
      ## Never add any GlobalSecondaryIndexes or associated KeySchemas or Projections
      ## Never add ProvisionedThroughput, as this does not work with PAY_PER_REQUEST.

[CELL_ID]:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-[CELL_ID]
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: [CELL_ID]
      CodeUri: ../../working/[CELL_ID] ## Do not change this line
      Handler: index.handler
      Runtime: nodejs18.x
      Events:
        # Example HTTP methods
        HttpApiGET:
          Type: HttpApi
          Properties:
            Path: /{[Update with id from guidance]}
            Method: GET
            ApiId: !Ref [CELL_ID]HttpApi
        HttpApiGETMultiple:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
            ApiId: !Ref [CELL_ID]HttpApi
        HttpApiPUT:
          Type: HttpApi
          Properties:
            Path: /{[Update with id from guidance]}
            Method: PUT
            ApiId: !Ref [CELL_ID]HttpApi
        HttpApiPOST:
          Type: HttpApi
          Properties:
            Path: /
            Method: POST
            ApiId: !Ref [CELL_ID]HttpApi
        HttpApiDELETE:
          Type: HttpApi
          Properties:
            Path: /{[Update with id from guidance]}
            Method: DELETE
            ApiId: !Ref [CELL_ID]HttpApi
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref [CELL_ID]Table
      Environment:
        Variables:
          TABLE_NAME: !Ref [CELL_ID]Table