version = 0.1

[o[SOLUTION_ID_SHORT]-[USERNAME_LOWER_LAST3]-d]
[o[SOLUTION_ID_SHORT]-[USERNAME_LOWER_LAST3]-d.deploy]
[o[SOLUTION_ID_SHORT]-[USERNAME_LOWER_LAST3]-d.deploy.parameters]
aws_account_number = "360520317360"
stack_name = "o[SOLUTION_ID_SHORT]-[USERNAME_LOWER_LAST3]-d"
s3_prefix = "o[SOLUTION_ID_SHORT]-[USERNAME_LOWER_LAST3]-d"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
disable_rollback = false

[o[SOLUTION_ID_SHORT]-[USERNAME_LOWER_LAST3]-p]
[o[SOLUTION_ID_SHORT]-[USERNAME_LOWER_LAST3]-p.deploy]
[o[SOLUTION_ID_SHORT]-[USERNAME_LOWER_LAST3]-p.deploy.parameters]
aws_account_number = "360520317360"
stack_name = "o[SOLUTION_ID_SHORT]-[USERNAME_LOWER_LAST3]-p"
s3_prefix = "o[SOLUTION_ID_SHORT]-[USERNAME_LOWER_LAST3]-p"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
disable_rollback = false