[o-[SOLUTION_ID_SHORT]]
[o-[SOLUTION_ID_SHORT].deploy]
[o-[SOLUTION_ID_SHORT].deploy.parameters]
aws_account_number = "360520317360"
stack_name = "[SOLUTION_ID_SHORT]"
s3_prefix = "[SOLUTION_ID_SHORT]"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
disable_rollback = false